version: '3.9'
services:
  web:
    build: .
    volumes:
      - .:/MusicPlayer
      - static_volume:/MusicPlayer/staticfiles/
      - media_volume:/MusicPlayer/media/
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - '8000'
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/MusicPlayer/staticfiles/
      - media_volume:/MusicPlayer/media/
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: