# Generated by Django 5.0.3 on 2024-03-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_music_user_favorites_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='play_time',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
