# Generated by Django 5.0.3 on 2024-03-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reply',
        ),
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='review', to='reviews.review'),
        ),
    ]
